version: "3.5"

services:
  dashboard:
    container_name: cas-dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_URL: "http://example.org"
        LOGGER_URL: "http://example.org/logger"
        GITLAB_URL: "http://example.org/gitlab"
        TAIGA_URL: "http://example.org/taiga"
        MATTERMOST_URL: "http://example.org/mattermost"
        SONARQUBE_URL: "http://example.org/sonarqube"
    ports:
      - 8080:80
    volumes:
      - "/cas-dashboard/node_modules"
