version: '3.5'

services:
  dashboard:
    container_name: dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/cas-dashboard'
      - '/cas-dashboard/node_modules'
    environment:
      REACT_APP_BASE_PATH: "/dashboard"
    ports:
      - 9000:80
